### ISSUE TITLE
Riviera freezes on a black screen after the chapter 1 screen. (DSi)

### ISSUE THREAD

**Issue by UltyT** [FluBBaOfWard/NitroSwan#16]

**Comment by FluBBaOfWard** [comment]
Is this still an issue in V0.4.0?
If it is, can you please provide a save state right before the freeze, I don't really understand where the chapters start or end.

**Comment by UltyT** [comment]
Just checked v0.4.0 and v0.4.1 and it seems to be fixed.

**Comment by FluBBaOfWard** [comment]
Closing this for now.
