### ISSUE TITLE
Sound not working on Bad Apple!! demo

### ISSUE THREAD

**Issue by asiekierka** [FluBBaOfWard/NitroSwan#17]
The Bad Apple!! demo uses an HBLANK interrupt to stream wave audio to Channel 2 at 12000Hz. This works on real hardware and on Mednafen, but does not work on NitroSwan.

Tested on New 3DS in DSi mode.

Source code: https://github.com/asiekierka/bad-apple-for-wswan/tree/1a43f2784e664ba00026bfbaa65ca1c7c2aa422e
Download: https://asie.pl/files/wswan/bad_apple_ws.zip

**Comment by FluBBaOfWard** [comment]
I will hopefully fix this soon.

**Comment by asiekierka** [comment]
Thank you! Hope the source code availability helps. If you have any questions, feel free to ask!

**Comment by FluBBaOfWard** [comment]
Can this be closed now?

**Comment by asiekierka** [comment]
This specific issue yes, but...

With "Allow Refresh Change: Off", the sound seems slowed down - kind of as if it was updating at 60Hz and not 75.47Hz.

With "Allow Refresh Change: On", the sound seems fine, but my 3DS seems to skip frames wildly - I do not have a proper DSi to test whether it's the fault of 3DS TWL_FIRM's frame copying logic or the emulator, but I suspect it would be a good idea to implement a proper frameskip system.
