### ISSUE TITLE
 if u can do this ty can u X1-X4 on L trigger and  Y button and Y1-Y4 on X and R trigger

### ISSUE THREAD

**Issue by Rnzei** [FluBBaOfWard/NitroSwan#33]
Here's and example
X1-X2 for L (left) and Y(right)
Y1-Y4 for X (down) and R (up)
Some games like fighting games on the wonderswan is hard to do inputs when using the hold L Mapp and this is more comfortable to use if not can u tell me why and I'll understand it

**Comment by FluBBaOfWard** [comment]
Please explain more, exactly which buttons do you want to be pressed on the WonderSwan when you press which buttons on the NDS? Is this for a specific game, please name them.

**Comment by Rnzei** [comment]
Here the thing there are some games need a better layout for gmaes like
action games that used both 2 dpad
I'm saying is that can u map the second dpad on x,y buttons L and R trigger
so we don't need to hold L

**Comment by Rnzei** [comment]
Hey flubar can u try add slot 2 support for D's lite so it can play more
games

**Comment by FluBBaOfWard** [comment]
So you want to map
NDS-R to WS-Y1
NDS-X to WS-Y2
NDS-Y to WS-Y3
NDS-L to WS-Y4
Is this correct?
So if you want to press up+left on the WS you press L+R on the NDS?
Should I remove open the menu on L+R and only use the touch screen for that?

**Comment by Rnzei** [comment]
Yes pretty much pls can u do it

**Comment by Rnzei** [comment]
Or just set menu on select button

**Comment by FluBBaOfWard** [comment]
This should be fixed in the next release.
