### ISSUE TITLE
Hey flubba can u add slot 2 support on the ds and Ds lite for more games can work on the ds 

### ISSUE THREAD

**Issue by Rnzei** [FluBBaOfWard/NitroSwan#34]
Hello flubba I have and Ds browser expansion pak
Pls can u add a slot 2 support pls nitroswan and ngpds too

**Comment by asiekierka** [comment]
The performance of the expansion pak's memory is most likely insufficient to run the emulator at full speed.

**Comment by Rnzei** [comment]
ahh ok but can you make it to use the expansion pak to load biger games?

**Comment by FluBBaOfWard** [comment]
This should be fixed now.

**Comment by Rnzei** [comment]
Hey flubba ty for listening and btw ur ngpds could actually use the code of
the expansion pack theres 2 games that need it both is the best games of
the neo geo pocket
