### ISSUE TITLE
Fix controls for Pocket Challenge V2

### ISSUE THREAD

**Issue by soundsnow** [FluBBaOfWard/NitroSwan#35]
WonderSwan|PocketChallenge V2
:---:|:---:
y1|clear
y2|(always held)
y3|circle
y4|pass
x1|view
x2|(always held)
x3|escape
x4|rightLatch
(unconnected)|leftLatch
start|(always held)
a|down
b|up

"unconnected" means this bit in the control pad register is not wired to a physical button, so it's always 0 and cannot be pressed.

"always held" means this bit in the control pad register is not wired to a physical button, it's always 1 and cannot be un-pressed.

extensions: "pc2", "pcv2"

system: Benesse - Pocket Challenge V2

pass and clear
question: Which is on the left? which one is on the right?
answer: "pass→circle→clear"

![image254](https://user-images.githubusercontent.com/109885044/232264714-3e6b8588-f316-46e3-8795-bdf2316f81fb.png)

**Comment by FluBBaOfWard** [comment]
Thank you very much for this info, I will try to fix this as soon as possible.

**Comment by FluBBaOfWard** [comment]
Is this ok now? Can this issue be closed?
