### ISSUE TITLE
File is too large!

### ISSUE THREAD

**Issue by DQW1R2V3** [FluBBaOfWard/NitroSwan#42]
I've been using Mr. Flubba emulators so long since I got myself a Nintendo DS, and don't matter what I try to do, never managed to run ROMs above 2mb on nitroswan. There's a way to fix it? Or I am just being fool for doing something wrong and I didn't noticed yet? 😅
Thanks in advance and keep up the good job! 👍
Edit: it's regarding Makai Toushi SaGa original and English translation both ain't run without the "file too large!" message.

Greetings, D.Q

**Comment by FluBBaOfWard** [comment]
The DS has 4MB of RAM, this is where the emulator plus the game must fit, this can be remedied by adding a SLOT-2/GBA cart with RAM. The DSi/3DS on the other hand already has 16MB.

**Comment by FluBBaOfWard** [comment]
Fixed documentation.

**Comment by catchem88** [comment]
@FluBBaOfWard sorry I'm a noob in DS homebrew scene. I got the same error message on NitroSwan but I'm running it on R4 card in O2DS, I believe that means it's running on DS mode? No way around that right? Since the 2DS doesn't have a GBA slot
