### ISSUE TITLE
DSi XL - File too large! with Final Fantasy I & II English Patched

### ISSUE THREAD

**Issue by mikhaelcool7** [FluBBaOfWard/NitroSwan#45]
Each game is 4MB in size but still fail to load

**Comment by FluBBaOfWard** [comment]
Make sure you are running in DSi mode.

**Comment by mikhaelcool7** [comment]
For those that come across this at a later point. Take out the MicroSD card from your flashcart, insert it into an SD Card adapter that fits into the DSi/DSi XL, insert it into the DSi/DSi XL, hold A+B to boot into Filemenu (Unlaunch must be installed), scroll down until you see NitroSwan and start it. This will start it in DSi Mode. Filemenu sorts the MicroSD card files by date added - descending and not in alphabetical.
