### ISSUE TITLE
Kaze no Klonoa: Moonlight Museum (English Patched) WonderSwan - Not Saving

### ISSUE THREAD

**Issue by mikhaelcool7** [FluBBaOfWard/NitroSwan#46]
Played for about an hour, returned back, booted my DSi XL and the game has no saves to load. The nitroswan folder is at the root of the MicroSD card and the emulator settings do save there as well as my save states.

**Comment by FluBBaOfWard** [comment]
Since you're not mentioning the "Save NVRAM" menu item I guess you missed to use that?

**Comment by mikhaelcool7** [comment]
> Since you're not mentioning the "Save NVRAM" menu item I guess you missed to use that?

Yes, that does find and read the save data
