### ISSUE TITLE
fix readme for pocket challenge v2 right button

### ISSUE THREAD

**Issue by AngelofMe** [FluBBaOfWard/NitroSwan#48]
Dpad is mapped to up, down, left & right.
It should be 
Dpad is mapped to up, down, right & right.
Because WonderSwan has no left button for Pocket Challenge V2
Yes, he said
https://user-images.githubusercontent.com/109885044/232264714-3e6b8588-f316-46e3-8795-bdf2316f81fb.png

**Comment by FluBBaOfWard** [comment]
According to the only documentation I've seen "Left" on PCV2 is mapped to bit0 on row 2, this is not used on WonderSwan.
[Keypad info](https://ws.nesdev.org/wiki/Keypad)
If you have any other info please provide it & I will open the issue again.
